name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ✅ Checkout repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # ✅ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # ✅ Install dependencies & run lint/tests
    - name: Install Dependencies
      run: |
        pip install flake8
        pip install -r requirements.txt

    - name: Lint Code
      run: |
        flake8 src --max-line-length=120

    # ✅ Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ✅ Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/california-housing-api:latest .

    # ✅ Push Image to Docker Hub
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/california-housing-api:latest
